-- Theme: tokyonight
-- Generated by theme-switch

local M = {}

M.name = "tokyonight"

M.colors = {
    bg = "#24283b",
    bg_dark = "#1f2335",
    bg_light = "#3b4261",
    fg = "#c0caf5",
    fg_dark = "#a9b1d6",
    fg_muted = "#565f89",
    accent = "#7aa2f7",
    secondary = "#bb9af7",
    red = "#f7768e",
    orange = "#ff9e64",
    yellow = "#e0af68",
    green = "#9ece6a",
    cyan = "#7dcfff",
    blue = "#7aa2f7",
    magenta = "#bb9af7",
    border = "#3b4261",
    selection = "#33467c",
    cursor = "#c0caf5",
}

function M.apply()
    local c = M.colors

    vim.cmd("highlight clear")
    vim.o.background = "dark"
    vim.g.colors_name = "tokyonight"

    local highlights = {
        -- UI
        Normal = { fg = c.fg, bg = c.bg },
        NormalFloat = { fg = c.fg, bg = c.bg_dark },
        FloatBorder = { fg = c.border, bg = c.bg_dark },
        Cursor = { fg = c.bg, bg = c.cursor },
        CursorLine = { bg = c.bg_light },
        CursorLineNr = { fg = c.accent, bold = true },
        LineNr = { fg = c.fg_muted },
        SignColumn = { bg = c.bg },
        ColorColumn = { bg = c.bg_dark },
        Visual = { bg = c.selection },
        VisualNOS = { bg = c.selection },
        Search = { fg = c.bg, bg = c.yellow },
        IncSearch = { fg = c.bg, bg = c.orange },

        -- Popup menu
        Pmenu = { fg = c.fg, bg = c.bg_dark },
        PmenuSel = { fg = c.fg, bg = c.selection },
        PmenuSbar = { bg = c.bg_light },
        PmenuThumb = { bg = c.accent },

        -- Messages
        ErrorMsg = { fg = c.red },
        WarningMsg = { fg = c.yellow },
        MoreMsg = { fg = c.cyan },
        Question = { fg = c.cyan },

        -- Splits and tabs
        VertSplit = { fg = c.border },
        WinSeparator = { fg = c.border },
        TabLine = { fg = c.fg_muted, bg = c.bg_dark },
        TabLineSel = { fg = c.fg, bg = c.bg },
        TabLineFill = { bg = c.bg_dark },

        -- Statusline
        StatusLine = { fg = c.fg, bg = c.bg_dark },
        StatusLineNC = { fg = c.fg_muted, bg = c.bg_dark },

        -- Syntax
        Comment = { fg = c.fg_muted, italic = true },
        Constant = { fg = c.orange },
        String = { fg = c.green },
        Character = { fg = c.green },
        Number = { fg = c.orange },
        Boolean = { fg = c.orange },
        Float = { fg = c.orange },
        Identifier = { fg = c.fg },
        Function = { fg = c.blue },
        Statement = { fg = c.magenta },
        Conditional = { fg = c.magenta },
        Repeat = { fg = c.magenta },
        Label = { fg = c.cyan },
        Operator = { fg = c.fg_dark },
        Keyword = { fg = c.magenta },
        Exception = { fg = c.magenta },
        PreProc = { fg = c.cyan },
        Include = { fg = c.magenta },
        Define = { fg = c.magenta },
        Macro = { fg = c.cyan },
        PreCondit = { fg = c.cyan },
        Type = { fg = c.cyan },
        StorageClass = { fg = c.magenta },
        Structure = { fg = c.cyan },
        Typedef = { fg = c.cyan },
        Special = { fg = c.secondary },
        SpecialChar = { fg = c.secondary },
        Tag = { fg = c.accent },
        Delimiter = { fg = c.fg_dark },
        SpecialComment = { fg = c.fg_muted },
        Debug = { fg = c.red },
        Underlined = { underline = true },
        Error = { fg = c.red },
        Todo = { fg = c.bg, bg = c.yellow, bold = true },

        -- Diff
        DiffAdd = { bg = "#1a332a" },
        DiffChange = { bg = "#1a2a33" },
        DiffDelete = { bg = "#331a1a" },
        DiffText = { bg = "#1a3a4a" },

        -- Git signs
        GitSignsAdd = { fg = c.green },
        GitSignsChange = { fg = c.yellow },
        GitSignsDelete = { fg = c.red },

        -- Diagnostics
        DiagnosticError = { fg = c.red },
        DiagnosticWarn = { fg = c.yellow },
        DiagnosticInfo = { fg = c.cyan },
        DiagnosticHint = { fg = c.accent },
        DiagnosticUnderlineError = { undercurl = true, sp = c.red },
        DiagnosticUnderlineWarn = { undercurl = true, sp = c.yellow },
        DiagnosticUnderlineInfo = { undercurl = true, sp = c.cyan },
        DiagnosticUnderlineHint = { undercurl = true, sp = c.accent },

        -- Treesitter
        ["@variable"] = { fg = c.fg },
        ["@variable.builtin"] = { fg = c.red },
        ["@variable.parameter"] = { fg = c.fg },
        ["@constant"] = { fg = c.orange },
        ["@constant.builtin"] = { fg = c.orange },
        ["@module"] = { fg = c.cyan },
        ["@label"] = { fg = c.cyan },
        ["@string"] = { fg = c.green },
        ["@character"] = { fg = c.green },
        ["@number"] = { fg = c.orange },
        ["@boolean"] = { fg = c.orange },
        ["@type"] = { fg = c.cyan },
        ["@type.builtin"] = { fg = c.cyan },
        ["@attribute"] = { fg = c.cyan },
        ["@property"] = { fg = c.accent },
        ["@function"] = { fg = c.blue },
        ["@function.builtin"] = { fg = c.blue },
        ["@function.method"] = { fg = c.blue },
        ["@constructor"] = { fg = c.cyan },
        ["@keyword"] = { fg = c.magenta },
        ["@keyword.function"] = { fg = c.magenta },
        ["@keyword.return"] = { fg = c.magenta },
        ["@keyword.operator"] = { fg = c.magenta },
        ["@keyword.import"] = { fg = c.magenta },
        ["@keyword.conditional"] = { fg = c.magenta },
        ["@keyword.repeat"] = { fg = c.magenta },
        ["@operator"] = { fg = c.fg_dark },
        ["@punctuation"] = { fg = c.fg_dark },
        ["@punctuation.bracket"] = { fg = c.fg_dark },
        ["@punctuation.delimiter"] = { fg = c.fg_dark },
        ["@comment"] = { fg = c.fg_muted, italic = true },
        ["@tag"] = { fg = c.accent },
        ["@tag.attribute"] = { fg = c.secondary },
        ["@tag.delimiter"] = { fg = c.fg_dark },
    }

    for group, opts in pairs(highlights) do
        vim.api.nvim_set_hl(0, group, opts)
    end
end

return M
